# Generated by Django 3.2.7 on 2021-09-01 11:57

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, verbose_name='名前')),
                ('name_furigana', models.CharField(default='', max_length=20, verbose_name='ふりがな')),
                ('entering_date', models.DateTimeField(blank=True, null=True, verbose_name='入社日')),
                ('retirement_date', models.DateTimeField(blank=True, null=True, verbose_name='退職日')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日')),
            ],
        ),
    ]
